# Docs: https://www.appveyor.com/docs/appveyor-yml/

# version format
version: 1.0.{build}-{commitId}

# branches to build
branches:
  # whitelist
  #include:
  #  - main
  #  - production

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
#skip_tags: true

# Start builds on tags only (GitHub, BitBucket, GitLab, Gitea)
skip_non_tags: true

# Skipping commits with particular message or from specific user
#skip_commits:
#  message: /(ci\(*\):|ci:)/      # Regex for matching commit message

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - '*/docs/*'
    - '**/*.html'

# Including commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
#only_commits:
#  files:
#    - Project-A/
#    - Project-B/

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

configuration:
- Debug
- Release

assembly_info:
  patch: true
  file: 'spv3\loader\src\properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: 'spv3\loader\src\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
- git submodule init
- git submodule update

nuget:
  project_feed: true
before_build:
- nuget restore

build:
  project: 'spv3\loader\src\spv3.sln'
  parallel: true
  verbosity: minimal

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
    # Deploy to GitHub Releases
#deploy:
#  - provider: GitHub
#    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#    draft: false
#    prerelease: false
#    on:
#      branch: main                # release from main branch only
#      APPVEYOR_REPO_TAG: true       # deploy on tag push only