name: main

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    #branches-ignore: [ gh-pages ]
    paths:
      #- ${{variable}}/**
      - .github/workflows/**
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: windows-latest

    env:
      isHXE: 0
      isSPV3: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ############
      # SETUP
      ############
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required by tj-actions/changed-files and GitVersion

        # https://github.com/marketplace/actions/changed-files
        # We use this to determine if an HXE or SPV3 release should be versioned and published.
      - name: Get changed files (HXE)
        id: changed-files-hxe
        uses: tj-actions/changed-files@v8
        with:
          files: hxe/kernel/src
      - name: Get changed files (SPV3)
        id: changed-files-spv3
        uses: tj-actions/changed-files@v8
        with:
          files: spv3/loader/src
      - name: Set isHXE
        if: steps.changed-files-hxe.outputs.any_changed
        run: isHXE = 1
      - name: Set isSPV3
        if: steps.changed-files-spv3.outputs.anychanged
        run: isSPV3 = 1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.x

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.x

        # https://github.com/marketplace/actions/gittools
      - name: Set up GitTools
        uses: GitTools/actions@v0.9.x
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.x
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.x
      - run: echo "${{ steps.gitversion.outputs.fullSemVer }}"

      #- name: Extract version from tag
      #  id: get-version
      #  uses: battila7/get-version-action@v2

      ############
      # BUILD
      ############
      
      - name: DotNet build prep
        run: dotnet build /p:ContinuousIntegrationBuild=true

      - name: Build
        run: dotnet build /p:Version="${{ steps.gitversion.outputs.assemblySemVer }}"
      - name: Pack
        run: dotnet pack /p:PackageVersion="${{ steps.gitversion.outputs.semVer \- steps.gitversion.outputs.shortSha }}"

      - name: Check for SPV3/HXE release cue
        if: isHXE == 1 && isSPV3 == 1
        run: echo "version and release mechanism"
