# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    #branches-ignore: [ gh-pages ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ############
      # SETUP
      ############
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required by tj-actions/changed-files and GitVersion

        # https://github.com/marketplace/actions/changed-files
        # We use this to determine if an HXE or SPV3 release should be versioned and published.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8
        with:
          files: |
          hxe/kernel/src
          spv3/loader/src
      - name: Set isHXE
        run: step.changed-files
      - name: Set isSPV3
        run: steps.changed-files

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.x

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.x

        # https://github.com/marketplace/actions/gittools
      - name: Set up GitTools
        uses: GitTools/actions@v0.9.x
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.x
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.x
      - run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

#      - name: Extract version from tag
#        id: get-version
#        uses: battila7/get-version-action@v2

      ############
      # BUILD
      ############
      
      - name: DotNet build prep
        run: dotnet build /p:ContinuousIntegrationBuild=true

      - name: Build
        run: dotnet build /p:Version="${{ steps.gitversion.outputs.fullSemVer }}"
      - name: Pack
        run: dotnet pack /p:PackageVersion="${{ steps.gitversion.outputs.fullSemVer }.{ steps.gitversion.outputs.shortSha }}"

