name: Release @halospv3/shared

on:
  push:
    branches: [ halospv3/shared ]
    paths:
    - 'package.json'
    - 'package-lock.json'
    - '.releaserc.yaml'
  workflow_dispatch:
    
jobs:
  publish:
    name: Publish halospv3/shared
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - run: npm install

    - name: Semantic Release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
